name: CI — TypeScript, ESLint, Prettier

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checks:
    name: Runs type, lint, and format checks
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [24]
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Type-check (no emit)
        run: pnpm tsc

      - name: Check code formatting
        run: pnpm format

      - name: Lint with ESLint
        run: pnpm lint:strict
